version: "3"

services:
  crawler:
    build: ./crawler
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db/crawler_db
    volumes:
      - crawler_control:/app/control

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=crawler_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db/crawler_db
    volumes:
      - crawler_control:/app/control

volumes:
  mysql_data:
  crawler_control:
